 bitcore-db:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - /srv/docker/mongodb:/data/db
  networks:
    - bitcore   
  #restart: always

wallet-service:
  image: quay.io/interactar/bitcorewalletservice:master
  ports:
    - "3232:3232"
  volumes:
    - ./walletcfg/config.js:/bws/config.js
      #  volumes_from:
      #    - db
  networks:
    - bitcore   
  links:
    - bitcore-db

networks:
 bitcore:
     driver: bridge
